---
- hosts: ghost.live
  name: Install & Set MySQL
  tasks:
    - name: Installo i pacchetti necessari
      apt:
        name: ['software-properties-common', 'dirmngr', 'python3-pymysql']
        state: present
    - name: Installo MySQL
      apt:
        name: ['mysql-server']
        state: present
    - name: Abilito Systemd
      systemd:
        name: mysql
        daemon_reload: yes
        enabled: yes
    - name: mysqld restart
      service:
        name: mysql
        state: restarted
    - name: Modifico root password
      mysql_user:
        name: root
        password: '{{ mysql_root_password }}'
        login_unix_socket: /run/mysqld/mysqld.sock
        state: present
    - name: Creo .my.cnf
      copy:
        content: |
          [client]
          user=root
          password={{ mysql_root_password }}
        dest: ~/.my.cnf
        force: yes 
    - name: Rimuovo tutti gli utenti anonimi
      mysql_user:
        name: ''
        host_all: yes
        state: absent
