---
- hosts: ghost.live
  name: Creo un blog ghost
  tasks:
    - name: Creo la cartella {{ site_path }}
      file:
        path: "/var/www/{{ site_path }}"
        state: directory
        mode: '0775'
        owner: demo
        group: demo
    - name: Creo il database
      mysql_db:
        name: "{{ ghost_db_name }}"
        state: present
    - name: Creo l'utente ghost
      mysql_user:
        name: "{{ ghost_db_user }}"
        password: "{{ ghost_db_password }}"
        host: "{{ ghost_db_host }}"
        login_host: "{{ ghost_db_host }}"
        priv: "{{ ghost_db_name }}.*:ALL"
        state: present
    - name: Installo ghost
      shell: "ghost install --url={{ ghost_project_url }} --db={{ ghost_db }} --dbhost={{ ghost_db_host }} --dbuser={{ ghost_db_user }} --dbpass={{ ghost_db_password }} --dbname={{ ghost_db_name }} --mail={{ ghost_smtp }} --mailservice={{ ghost_smtp_service }} --mailuser={{ ghost_smtp_user }} --mailpass={{ ghost_smtp_password }} --mailport={{ ghost_smtp_port }} --sslemail={{ ghost_letsencrypt_user }} --no-setup-ssl --no-stack --no-prompt --start"
      become: true
      become_user: demo
      args:
        chdir: "/var/www/{{ site_path }}"
